version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: dockerfile
      args: 
        - IRIS_PASSWORD=$IRIS_PASSWORD
    command: --check-caps false
    restart: always
    env_file: 
      - .env
    ports: 
      - 45450:1972
      - 45451:52773
      - 45452:53773
    volumes:
      - ./:/irisdev/app